version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    container_name: "my_postgres"
    environment:
    - POSTGRES_PASSWORD=12345
    - POSTGRES_USER=user
    - POSTGRES_DB=database
    volumes:
    - D:\Data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
